# Use an official Python runtime as a parent image
FROM python:3.10

# Set the working directory in the container
WORKDIR /app

# Copy the model training script into the container
COPY src/ .

# Install Scikit-Learn and joblib
RUN pip install -r requirements.txt

# Expose FastAPI default port
EXPOSE 8000

# Train the model at build time so it's ready to serve
RUN python main.py

# Launch the FastAPI server when the container starts
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
